### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by justay** [wendal/go-oci8#2]
under go 1.6, it will raise a error: 
`C:\Go\src\github.com\wendal\go-oci8\oci8.go:116: cannot convert (**C.struct_OCIServer)(unsafe.Pointer(&conn.svc)) (type **C.struct_OCIServer) to type **C.struct_OCISvcCtx`

Is there any solution for this problem?

**Comment by wendal** [comment]
use this https://github.com/mattn/go-oci8

**Comment by wendal** [comment]
请到 https://github.com/mattn/go-oci8 报issue
