### ISSUE TITLE
my   instantclient_12_2 is  32bit, MinGW  is "x86_64-4.8.2-release-posix-seh-rt_v3-rev4" 

### ISSUE THREAD

**Issue by gftao** [wendal/go-oci8#5]
# gooci
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\\instantclient_12_2\\sdk\\lib\\msvc/oci.lib when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/instantclient_12_2/oci.dll when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\\instantclient_12_2\\sdk\\lib\\msvc/oci.lib when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\\instantclient_12_2\\sdk\\lib\\msvc\oci.lib when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/instantclient_12_2/oci.dll when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\\instantclient_12_2\\sdk\\lib\\msvc/oci.lib when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/instantclient_12_2/oci.dll when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\\instantclient_12_2\\sdk\\lib\\msvc/oci.lib when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\\instantclient_12_2\\sdk\\lib\\msvc\oci.lib when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/instantclient_12_2/oci.dll when searching for -loci
C:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -loci
collect2.exe: error: ld returned 1 exit status

**Comment by wendal** [comment]
pls report to https://github.com/mattn/go-oci8

**Comment by wendal** [comment]
BTW, you shall use mingw 32
