### ISSUE TITLE
GetAffectRow和GetLastInsertID获取数据不准确

### ISSUE THREAD

**Issue by Dot-Liu** [wendal/go-oci8#8]
感谢作者将mattn重新封装，但美中不足的是GetAffectRow和GetLastInsertID两个方法是有问题的，获取到的数皆为0

**Comment by wendal** [comment]
用 https://github.com/mattn/go-oci8

**Comment by Dot-Liu** [comment]
嗯，发现该问题的时候我已经转mattn了，修改了mattn的部分变量就通了
